version: '2'
services:
  fedex:
    image: "sidharder/ap-fedex:latest"
    container_name: "ap-fedex"
    ports:
      - "50052:50052"
    environment:
      - AP_FEDEX_SERVICE_BINDING=0.0.0.0:50052
      - AP_MYSQL_SERVICE_BINDING=mysql:50053

  mysql:
    image: "sidharder/ap-mysql:latest"
    container_name: "ap-mysql"
    ports:
      - "50053:50053"
    environment:
      - AP_MYSQL_SERVICE_BINDING=0.0.0.0:50053
      - AP_MYSQL_HOST=10.1.2.26
      - AP_MYSQL_USER=sqldude
      - AP_MYSQL_PASS=123Whatsup
      - AP_MYSQL_DATABASE=lis

  job-runner:
    image: "sidharder/ap-job-runner:latest"
    container_name: "ap-job-runner"
    environment:
      - AP_FEDEX_SERVICE_BINDING=fedex:50052
